apiVersion: v1
kind: Pod
metadata:
  name: kopia
  labels:
    name: kopia
spec:
  containers:
  - name: kopia
    image: kopia/kopia:latest
    volumeMounts:
      - mountPath: /var/jenkins_home
        name: jenkins-data
    command:
      - sleep
    args:
      - "6000"
  volumes:
    - name: jenkins-data
      hostPath:
        path: /data/jenkins-volume/
